on:
  release:
    types: [published]

jobs:
  build:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/hardwatt-org/hardwatt-pocketbase:latest,ghcr.io/hardwatt-org/hardwatt-pocketbase:${{ github.event.release.tag_name }}
